apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mlsecops-retraining-pipeline-
  namespace: argo-workflows
spec:
  entrypoint: main-retraining-pipeline
  serviceAccountName: argo-workflow

  podSpecPatch: |
    containers:
    - name: main
      env:
      - name: AWS_ROLE_ARN
        value: ""
      - name: AWS_WEB_IDENTITY_TOKEN_FILE
        value: ""
      - name: AWS_EC2_METADATA_DISABLED
        value: "false"

  # Pipeline parameters
  arguments:
    parameters:
      - name: image-tag
        value: "v0.0.1"
      - name: ecr-registry
        value: "625715126488.dkr.ecr.us-east-1.amazonaws.com/registry"
      - name: mlflow-tracking-uri
        value: "http://mlflow.mlflow.svc.cluster.local:5000"
      - name: s3-artifact-bucket
        value: "mlsecops-workflows-artifacts"
      - name: dynamodb-table
        value: "silver-table"
      - name: s3-production-bucket
        value: "mlsecops-production-data"
      - name: max-items
        value: "1000"  # Limit number of records to fetch (empty = unlimited)
      - name: replay-ratio
        value: "0.3"  # Replay 30% of old training data

  templates:
    - name: main-retraining-pipeline
      steps:
        # Step 1: Prepare data (parallel)
        - - name: prepare-data
            template: prepare-data-parallel

        # Step 2: Merge new data with old data replay
        - - name: merge-data
            templateRef:
              name: template-merge-data
              template: merge-data
            arguments:
              parameters:
                - name: ecr-registry
                  value: "{{workflow.parameters.ecr-registry}}"
                - name: image-tag
                  value: "merge_data-{{workflow.parameters.image-tag}}"
                - name: s3-artifact-bucket
                  value: "{{workflow.parameters.s3-artifact-bucket}}"
                - name: workflow-name
                  value: "{{workflow.name}}"
                - name: replay-ratio
                  value: "{{workflow.parameters.replay-ratio}}"

        # Step 3: Validate data
        - - name: validate-data
            templateRef:
              name: template-validate-data
              template: validate-data
            arguments:
              parameters:
                - name: ecr-registry
                  value: "{{workflow.parameters.ecr-registry}}"
                - name: image-tag
                  value: "validate_data-{{workflow.parameters.image-tag}}"
                - name: s3-artifact-bucket
                  value: "{{workflow.parameters.s3-artifact-bucket}}"
                - name: workflow-name
                  value: "{{workflow.name}}"

        # Step 4: Preprocess data
        - - name: preprocess-data
            templateRef:
              name: template-preprocess-prod-data
              template: preprocess-prod-data
            arguments:
              parameters:
                - name: ecr-registry
                  value: "{{workflow.parameters.ecr-registry}}"
                - name: image-tag
                  value: "preprocess_data-{{workflow.parameters.image-tag}}"
                - name: s3-artifact-bucket
                  value: "{{workflow.parameters.s3-artifact-bucket}}"
                - name: workflow-name
                  value: "{{workflow.name}}"

        # Step 5: Retrain models (parallel)
        - - name: retrain-models
            template: retrain-parallel

        # Step 6: Compare models
        - - name: compare-models
            templateRef:
              name: template-compare-models
              template: compare-models
            arguments:
              parameters:
                - name: ecr-registry
                  value: "{{workflow.parameters.ecr-registry}}"
                - name: image-tag
                  value: "compare_models-{{workflow.parameters.image-tag}}"
                - name: mlflow-tracking-uri
                  value: "{{workflow.parameters.mlflow-tracking-uri}}"

    - name: prepare-data-parallel
      parallelism: 2
      steps:
        - - name: fetch-prod-data
            templateRef:
              name: template-fetch-prod-data
              template: fetch-prod-data
            arguments:
              parameters:
                - name: ecr-registry
                  value: "{{workflow.parameters.ecr-registry}}"
                - name: image-tag
                  value: "fetch_prod_data-{{workflow.parameters.image-tag}}"
                - name: dynamodb-table
                  value: "{{workflow.parameters.dynamodb-table}}"
                - name: s3-artifact-bucket
                  value: "{{workflow.parameters.s3-artifact-bucket}}"
                - name: workflow-name
                  value: "{{workflow.name}}"
                - name: max-items
                  value: "{{workflow.parameters.max-items}}"
          - name: get-base-data
            templateRef:
              name: template-get-base-data
              template: get-base-data
            arguments:
              parameters:
                - name: s3-artifact-bucket
                  value: "{{workflow.parameters.s3-artifact-bucket}}"
                - name: workflow-name
                  value: "{{workflow.name}}"
                - name: s3-bucket
                  value: "{{workflow.parameters.s3-production-bucket}}"

    - name: retrain-parallel
      parallelism: 2
      steps:
        - - name: retrain-random-forest
            templateRef:
              name: template-retrain-rf
              template: retrain-rf
            arguments:
              parameters:
                - name: ecr-registry
                  value: "{{workflow.parameters.ecr-registry}}"
                - name: image-tag
                  value: "retrain_rf-{{workflow.parameters.image-tag}}"
                - name: mlflow-tracking-uri
                  value: "{{workflow.parameters.mlflow-tracking-uri}}"
                - name: s3-artifact-bucket
                  value: "{{workflow.parameters.s3-artifact-bucket}}"
                - name: workflow-name
                  value: "{{workflow.name}}"
          - name: retrain-xgboost
            templateRef:
              name: template-retrain-xgb
              template: retrain-xgb
            arguments:
              parameters:
                - name: ecr-registry
                  value: "{{workflow.parameters.ecr-registry}}"
                - name: image-tag
                  value: "retrain_xgb-{{workflow.parameters.image-tag}}"
                - name: mlflow-tracking-uri
                  value: "{{workflow.parameters.mlflow-tracking-uri}}"
                - name: s3-artifact-bucket
                  value: "{{workflow.parameters.s3-artifact-bucket}}"
                - name: workflow-name
                  value: "{{workflow.name}}"
