apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mlsecops-training-pipeline-
  namespace: argo-workflows
spec:
  entrypoint: main-pipeline
  serviceAccountName: argo-workflow

  podSpecPatch: |
    containers:
    - name: main
      env:
      - name: AWS_ROLE_ARN
        value: ""
      - name: AWS_WEB_IDENTITY_TOKEN_FILE
        value: ""
      - name: AWS_EC2_METADATA_DISABLED
        value: "false"

  # Pipeline parameters
  arguments:
    parameters:
      - name: image-tag
        value: "v0.0.2"
      - name: ecr-registry
        value: "625715126488.dkr.ecr.us-east-1.amazonaws.com"
      - name: mlflow-tracking-uri
        value: "http://mlflow.mlflow.svc.cluster.local:5000"
      - name: s3-artifact-bucket
        value: "mlsecops-workflows-artifacts"

  templates:
    - name: main-pipeline
      steps:
        - - name: prepare-data
            templateRef:
              name: template-prepare-data
              template: prepare-data
            arguments:
              parameters:
                - name: s3-artifact-bucket
                  value: "{{workflow.parameters.s3-artifact-bucket}}"
                - name: workflow-name
                  value: "{{workflow.name}}"

        - - name: validate
            templateRef:
              name: template-validate-data
              template: validate-data
            arguments:
              parameters:
                - name: ecr-registry
                  value: "{{workflow.parameters.ecr-registry}}"
                - name: image-tag
                  value: "validate_data-{{workflow.parameters.image-tag}}"
                - name: s3-artifact-bucket
                  value: "{{workflow.parameters.s3-artifact-bucket}}"
                - name: workflow-name
                  value: "{{workflow.name}}"

        - - name: preprocess
            templateRef:
              name: template-preprocess-data
              template: preprocess-data
            arguments:
              parameters:
                - name: ecr-registry
                  value: "{{workflow.parameters.ecr-registry}}"
                - name: image-tag
                  value: "preprocess_data-{{workflow.parameters.image-tag}}"
                - name: s3-artifact-bucket
                  value: "{{workflow.parameters.s3-artifact-bucket}}"
                - name: workflow-name
                  value: "{{workflow.name}}"

        - - name: train-models
            template: train-parallel

        # - - name: compare-models
        #     templateRef:
        #       name: template-compare-models
        #       template: compare-models

    - name: train-parallel
      parallelism: 2
      steps:
        - - name: train-random-forest
            templateRef:
              name: template-train-rf
              template: train-rf
            arguments:
              parameters:
                - name: ecr-registry
                  value: "{{workflow.parameters.ecr-registry}}"
                - name: image-tag
                  value: "train_rf-{{workflow.parameters.image-tag}}"
                - name: mlflow-tracking-uri
                  value: "{{workflow.parameters.mlflow-tracking-uri}}"
                - name: s3-artifact-bucket
                  value: "{{workflow.parameters.s3-artifact-bucket}}"
                - name: workflow-name
                  value: "{{workflow.name}}"
          - name: train-xgboost
            templateRef:
              name: template-train-xgb
              template: train-xgb
            arguments:
              parameters:
                - name: ecr-registry
                  value: "{{workflow.parameters.ecr-registry}}"
                - name: image-tag
                  value: "train_xgb-{{workflow.parameters.image-tag}}"
                - name: mlflow-tracking-uri
                  value: "{{workflow.parameters.mlflow-tracking-uri}}"
                - name: s3-artifact-bucket
                  value: "{{workflow.parameters.s3-artifact-bucket}}"
                - name: workflow-name
                  value: "{{workflow.name}}"
