FROM python:3.10-slim

WORKDIR /app

COPY src/requirements.validate_data.txt .

RUN pip install --no-cache-dir -r requirements.validate_data.txt

COPY src/ ./src/

ENV PYTHONPATH=/app/src

CMD ["python", "src/validate_data.py"]
