FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY src/requirements.train.txt .

RUN pip install --no-cache-dir -r requirements.train.txt

COPY src/ ./src/

ENV PYTHONPATH=/app/src

ENV MLFLOW_TRACKING_URI=""

CMD ["python", "src/train_rf.py"]
