FROM python:3.10-slim

WORKDIR /app

COPY src/requirements.preprocess_data.txt .

RUN pip install --no-cache-dir -r requirements.preprocess_data.txt

COPY src/ ./src/

ENV PYTHONPATH=/app/src

CMD ["python", "src/preprocess_data.py"]
