FROM python:3.10-slim

WORKDIR /app

COPY tools/ci/requirements.security_check.txt .

RUN pip install --no-cache-dir -r requirements.security_check.txt

COPY src/security_check.py ./src/
COPY src/utils/__init__.py ./src/utils/
COPY src/utils/workflows_artifacts_handler.py ./src/utils/

ENV PYTHONPATH=/app/src

CMD ["python", "src/security_check.py"]
