FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    mlflow==3.5.1 \
    boto3==1.41.0 \
    imbalanced-learn==0.14.0 \
    xgboost==3.1.1

ENTRYPOINT ["mlflow"]
