FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY tools/ci/requirements.train.txt .

RUN pip install --no-cache-dir -r requirements.train.txt boto3

COPY src/fetch_production_data.py ./src/

ENV PYTHONPATH=/app/src

ENV DYNAMODB_TABLE="silver-table"
ENV S3_BUCKET="mlsecops-production-data"
ENV AWS_REGION="us-east-1"

CMD ["python", "src/fetch_production_data.py"]
