FROM python:3.10-slim

WORKDIR /app

COPY src/requirements.ci.txt .
RUN pip install --no-cache-dir -r requirements.ci.txt

COPY src/ ./src/

ENV PYTHONPATH=/app/src

CMD ["python", "src/extract_features.py"]
