FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY tools/ci/requirements.validate_data.txt .

RUN pip install --no-cache-dir -r requirements.validate_data.txt

COPY src/merge_and_validate_data.py ./src/
COPY src/utils/__init__.py ./src/utils/
COPY src/utils/workflows_artifacts_handler.py ./src/utils/

ENV PYTHONPATH=/app/src

CMD ["python", "src/merge_and_validate_data.py"]
