apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: template-compare-models
  namespace: argo-workflows
spec:
  templates:
    - name: compare-models
      inputs:
        parameters:
          - name: ecr-registry
          - name: image-tag
          - name: mlflow-tracking-uri
      container:
        image: "{{inputs.parameters.ecr-registry}}:{{inputs.parameters.image-tag}}"
        command: [sh, -c]
        args:
          - |
            set -e
            echo "Starting model comparison..."
            python /app/src/compare_models.py
        env:
          - name: PYTHONUNBUFFERED
            value: "1"
          - name: MLFLOW_TRACKING_URI
            value: "{{inputs.parameters.mlflow-tracking-uri}}"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
