apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: template-prepare-data
  namespace: argo-workflows
spec:
  templates:
    - name: prepare-data
      inputs:
        parameters:
          - name: s3-artifact-bucket
          - name: workflow-name
          - name: s3-bucket
            value: "mlsecops-production-data"
          - name: s3-prefix
            value: "gold/sample"
          - name: s3-object
            value: "Base.csv"
      container:
        image: amazon/aws-cli:2.31.39
        command: [sh, -c]
        args:
          - |
            set -euo pipefail
            echo "Preparing workspace..."
            mkdir -p /tmp/workspace/data/raw

            SRC_URI="s3://{{inputs.parameters.s3-bucket}}/{{inputs.parameters.s3-prefix}}/{{inputs.parameters.s3-object}}"
            DST_PATH="/tmp/workspace/data/raw/Base.csv"

            echo "Copying $SRC_URI -> $DST_PATH"
            aws s3 cp "$SRC_URI" "$DST_PATH"

            echo "Data prepared."
            ls -lh /tmp/workspace/data/raw

            # Upload to workflow artifact bucket
            ARTIFACT_URI="s3://{{inputs.parameters.s3-artifact-bucket}}/{{inputs.parameters.workflow-name}}/data/raw/Base.csv"
            echo "Uploading to $ARTIFACT_URI"
            aws s3 cp "$DST_PATH" "$ARTIFACT_URI"
            
            echo "✓ Artifact uploaded successfully"

