apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: template-pull-data
  namespace: argo-workflows
spec:
  templates:
    - name: pull-data
      container:
        image: "python:3.10-slim"
        command: [sh, -c]
        args:
          - |
            set -e
            echo "Installing dependencies..."
            apt-get update -qq && apt-get install -y -qq git > /dev/null 2>&1
            pip install --no-cache-dir --timeout 120 -q dvc[s3]

            echo "Setting up workspace..."
            cd /workspace

            git config --global user.email "workflow@mlsecops.internal"
            git config --global user.name "MLSecOps Workflow"
            git init

            mkdir -p .dvc data/raw

            cat > .dvc/config << EOF
            [core]
                remote = storage
            ['remote "storage"']
                url = s3://mlsecops-fraud-dataset/
                no_traverse = false
            EOF

            unset AWS_ROLE_ARN
            unset AWS_WEB_IDENTITY_TOKEN_FILE

            cat > data.dvc << EOF
            outs:
            - md5: 171c4b0d5e276867d109878312eba489.dir
              size: 331004564
              nfiles: 6
              hash: md5
              path: data
            EOF

            echo "Pulling data from S3 via DVC..."
            dvc pull

            echo "Data pulled successfully!"
            echo "Contents:"
            ls -lh data/
            ls -lh data/raw/ || echo "No raw directory yet"
        volumeMounts:
          - name: workspace
            mountPath: /workspace
